apiVersion: apps/v1
kind: Deployment
metadata:
  name: hound
  namespace: __namespace__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hound
  template:
    metadata:
      labels:
        app: hound
    spec:
      containers:
        - name: hound
          image: '__docker_registry_server__/appveen:hound.1.0.0'
          env:
            - name: MONGO_AUTHOR_DBNAME 
              value: "odpConfig"
            - name: MONGO_APPCENTER_DBNAME 
              value: "appveen-Adam"
            - name: MONGO_LOGS_DBNAME 
              value: "odpLogs"
            - name: MONGO_AUTHOR_COLLECTION 
              value: "counters"
            - name: MONGO_APPCENTER_COLLECTION 
              value: "counters"
            - name: MONGO_LOGS_COLLECTION 
              value: "counters"
          envFrom:
          - configMapRef:
              name: config
